# -*- coding: utf-8 -*-
"""ECON_833_PS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVpC6tCb1pERA6dOrtH78pUlkyXL16U-
"""

# mounting google drive - colab
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
from pathlib import Path
DATA_PATH = Path('/content/drive/My Drive/ECON_833/PSID_data.dta')
raw = pd.read_stata(DATA_PATH)
YEAR_COL = 'year'
print(raw.shape)
raw.head()

""" Keep: male heads, age 25–60, hourly wage > $7; create: ln(wage), Educ, Age, Age2, race dummies
    New Data Frame incl. following vars + cleaning raws: ln(wage), Educ, Age, Age2, Black, Hispanic, OtherRace, year """

def clean_raw(df, min_age=25, max_age=60, min_wage=7.0):

    # keep only vars that we will use for Q3
    tempDF = df[[ 'hlabinc', 'hannhrs', 'hsex', 'hrace', 'age', 'hyrsed', YEAR_COL ]].copy()
    tempDF = tempDF.rename(columns={YEAR_COL: 'year'})

    # ensure numeric for variables that will be used for regression
    for k in ['hlabinc', 'hannhrs', 'hsex', 'hrace', 'age', 'hyrsed', 'year']:
        tempDF[k] = pd.to_numeric(tempDF[k], errors='coerce')

    # hourly wage (drop non+ hours/income)
    tempDF = tempDF[(tempDF['hannhrs']>0) & (tempDF['hlabinc']>0)]
    tempDF['wage'] = tempDF['hlabinc'] / tempDF['hannhrs']

    tempDF = tempDF[tempDF['hsex'] == 1] # male heads: hsex == 1
    tempDF = tempDF[(tempDF['age'] >= min_age) & (tempDF['age'] <= max_age)] # age 25–60
    tempDF = tempDF[tempDF['wage'] > float(min_wage)] # wage > $7/hr

    # drop NA, missings
    tempDF = tempDF.dropna(subset=['wage', 'hyrsed', 'age', 'hrace', 'year'])

    # Q3 variables
    out = pd.DataFrame()
    out['lnw']  = np.log(tempDF['wage'])
    out['Educ'] = tempDF['hyrsed']
    out['Age'] = tempDF['age']
    out['Age2'] = tempDF['age'] ** 2
    out['year'] = tempDF['year'].astype(int)

    # hrace: 1=White, 2=Black, 3=Native American, 4=Asian/PI, 5=Hispanic, 6/7=Other
    out['Black']     = np.where(tempDF['hrace'] == 2, 1, 0)
    out['Hispanic']  = np.where(tempDF['hrace'] == 5, 1, 0)
    out['OtherRace'] = np.where(tempDF['hrace'].isin([3, 4, 6, 7]), 1, 0)

    out = out.dropna().reset_index(drop=True)
    return out

clean = clean_raw(raw)
print(clean.shape)
print("Years available:", sorted(clean['year'].unique().tolist())[:10], "...")

print(clean.shape)
clean.head()

# Q2
# (a) check: There are no observations that do not meet the selection criteria above.
def check_a(df, min_age=25, max_age=60, min_wage=7.0):
    """ check: (1) age within [min_age, max_age]; (2) No missings or NAs in the variables; (3) wage>min_wage """
    assert df['Age'].min() >= min_age, "age below or lower bound obs exists"
    assert df['Age'].max() <= max_age, "age above or upper bound obs exists"
    cov_vars = ['lnw','Educ','Age','Age2','Black','Hispanic','OtherRace','year']
    assert df[cov_vars].isna().sum().sum() == 0, "missing exists"
    assert df['lnw'].min() > np.log(min_wage), "wage obs below min_wage exists"
    print("Q2(a) unit test passed")

# (b) Indicator variables are coded correctly (e.g., no values other than 0 or 1, sum to one across categories, etc.).
def check_b(df):
    """ ensure binary coding for race & across obs - race coding should be mutually exclusive"""
    for col in ['Black','Hispanic','OtherRace']:
        bad_vals = set(df[col].unique()) - {0, 1}
        assert len(bad_vals) == 0, f"{col} error: {bad_vals}"
    row_sum = df[['Black','Hispanic','OtherRace']].sum(axis=1)
    assert ((row_sum == 0) | (row_sum == 1)).all(), "error"
    print("Q2(b) unit test passed")

check_a(clean, min_age=25, max_age=60, min_wage=7.0)
check_b(clean)

import statsmodels.api as sm

years = [1971, 1980, 1990, 2000]
Xcols = ["const","Educ","Age","Age2","Black","Hispanic","OtherRace"]

def mle_loglik(residuals):
    """ log-likelihood MLE: sigma^2_hat = RSS / n, logLik = -n/2 * [ln(2π) + 1 + ln(RSS/n)]"""
    n = residuals.size
    rss = np.sum(residuals**2)
    sig2 = rss / n
    return -0.5 * n * (np.log(2*np.pi) + 1 + np.log(sig2))

for y in years:
    dft = clean.loc[clean["year"] == y].copy()

    # add the intercept
    dft["const"] = 1.0
    X = dft[Xcols].to_numpy()
    lnw = dft["lnw"].to_numpy()

    # OLS
    ols = sm.OLS(lnw, X, missing="drop").fit()
    beta = np.asarray(ols.params) # ols beta coef
    resid = ols.resid
    nobs = int(ols.nobs)

    # sigma and log-likelihood MLE
    sigma_mle = np.sqrt(np.mean(resid**2))
    loglik = mle_loglik(resid)

    # print
    beta_str = np.array2string(beta, precision=4, separator=' ')
    print(f"{y} (n={nobs})")
    print("MLE  β (const, Educ, Age, Age2, Black, Hispanic, OtherRace):")
    print(beta_str)
    print("OLS  β:")
    print(beta_str)
    print(f"sigma_MLE={sigma_mle:.4f} & logLik={loglik:.2f}\n")

import numpy as np
import statsmodels.api as sm
from scipy.optimize import minimize

def _neg_loglike_linear(theta, X, y):
    k = X.shape[1]
    beta   = theta[:k]
    logsig = theta[k]
    sigma  = np.exp(logsig)
    r = y - X @ beta
    n = y.size
    return 0.5*n*np.log(2*np.pi) + n*logsig + 0.5*np.sum((r/sigma)**2)

def mle_linear_normal(X, y, method="L-BFGS-B"):
    X = np.asarray(X, float); y = np.asarray(y, float)
    n, k = X.shape
    # OLS init
    beta0 = np.linalg.lstsq(X, y, rcond=None)[0]
    resid = y - X @ beta0
    sig0  = np.sqrt(max(np.mean(resid**2), 1e-12))
    x0    = np.r_[beta0, np.log(sig0)]
    bounds = [(None, None)]*k + [(np.log(1e-8), np.log(1e8))]
    opt = minimize(_neg_loglike_linear, x0, args=(X, y), method=method, bounds=bounds)
    if not opt.success:
        raise RuntimeError("MLE not converge: " + opt.message)
    th = opt.x
    return th[:k], np.exp(th[k])

def test_mle_vs_ols(clean_df, years=(1971,1980,1990,2000), tol=1e-6):
    Xcols = ["const","Educ","Age","Age2","Black","Hispanic","OtherRace"]
    for yr in years:
        d = clean_df[clean_df["year"]==yr].copy()
        if d.empty:
            print(f"[{yr}] no rows — skipping."); continue
        d["const"] = 1.0
        X = d[Xcols].to_numpy()
        y = d["lnw"].to_numpy()

        ols = sm.OLS(y, X, missing="drop").fit()
        beta_ols = np.asarray(ols.params)

        beta_mle, sigma_mle = mle_linear_normal(X, y, method="L-BFGS-B")
        diff = np.max(np.abs(beta_mle - beta_ols))
        print(f"[{yr}] max|β_MLE-β_OLS|={diff:.2e}, σ_MLE={sigma_mle:.4f}")
        assert diff < tol, f"Year {yr}: MLE and OLS differ by {diff:.2e} ≥ {tol}"
    print("verified that : MLE matches OLS for all years")

test_mle_vs_ols(clean)

!pip -q install pytest