# -*- coding: utf-8 -*-
"""ECON_833_PS4_pytest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENO1uvLbwG1as0JBLNSUT3NbrW5RzH7Y
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile psid_model.py
# import numpy as np
# import pandas as pd
# import statsmodels.api as sm
# from scipy.optimize import minimize
# 
# YEAR_COL = 'year'
# 
# # Q1: cleaning the data and create variables that needed for the regression purpose
# def clean_raw(df, min_age=25, max_age=60, min_wage=7.0):
#     # working copy uses the name tempDF (no 'use')
#     tempDF = df[['hlabinc','hannhrs','hsex','hrace','age','hyrsed', YEAR_COL]].copy()
#     tempDF = tempDF.rename(columns={YEAR_COL: 'year'})
# 
#     # numeric coercions
#     for k in ['hlabinc','hannhrs','hsex','hrace','age','hyrsed','year']:
#         tempDF[k] = pd.to_numeric(tempDF[k], errors='coerce')
# 
#     # hourly wage; keep valid rows
#     tempDF = tempDF[(tempDF['hannhrs']>0) & (tempDF['hlabinc']>0)]
#     tempDF['wage'] = tempDF['hlabinc'] / tempDF['hannhrs']
# 
#     # sample selection
#     tempDF = tempDF[tempDF['hsex']==1]
#     tempDF = tempDF[tempDF['age'].between(min_age, max_age)]
#     tempDF = tempDF[tempDF['wage'] > float(min_wage)]
# 
#     # drop missings
#     tempDF = tempDF.dropna(subset=['wage','hyrsed','age','hrace','year'])
# 
#     # build model-ready frame
#     out = pd.DataFrame()
#     out['lnw']  = np.log(tempDF['wage'])
#     out['Educ'] = tempDF['hyrsed']
#     out['Age']  = tempDF['age']
#     out['Age2'] = tempDF['age']**2
#     out['year'] = tempDF['year'].astype(int)
# 
#     # race dummies: 1=White, 2=Black, 3=Native American, 4=Asian, 5=Hispanic, 6/7=Other
#     out['Black'] = np.where(tempDF['hrace']==2, 1, 0)
#     out['Hispanic'] = np.where(tempDF['hrace']==5, 1, 0)
#     out['OtherRace'] = np.where(tempDF['hrace'].isin([3,4,6,7]), 1, 0)
#     return out.dropna().reset_index(drop=True)
# 
# # Q2: (a),(b)
# def check_a(df, min_age=25, max_age=60, min_wage=7.0):
#     assert df['Age'].min() >= min_age
#     assert df['Age'].max() <= max_age
#     must = ['lnw','Educ','Age','Age2','Black','Hispanic','OtherRace','year']
#     assert df[must].isna().sum().sum() == 0
#     assert df['lnw'].min() > np.log(min_wage)
# 
# def check_b(df):
#     for c in ['Black','Hispanic','OtherRace']:
#         assert set(df[c].unique()).issubset({0,1})
#     s = df[['Black','Hispanic','OtherRace']].sum(axis=1)
#     assert ((s==0) | (s==1)).all()
# 
# # Q3: MLE
# def _neg_loglike_linear(theta, X, y):
#     k = X.shape[1]
#     beta   = theta[:k]
#     logsig = theta[k]
#     sigma  = np.exp(logsig)
#     r = y - X @ beta
#     n = y.size
#     return 0.5*n*np.log(2*np.pi) + n*logsig + 0.5*np.sum((r/sigma)**2)
# 
# def mle_linear_normal(X, y, method="L-BFGS-B"):
#     X = np.asarray(X, float); y = np.asarray(y, float)
#     n, k = X.shape
#     beta0 = np.linalg.lstsq(X, y, rcond=None)[0]
#     resid = y - X @ beta0
#     sig0  = np.sqrt(max(np.mean(resid**2), 1e-12))
#     x0    = np.r_[beta0, np.log(sig0)]
#     bounds = [(None, None)]*k + [(np.log(1e-8), np.log(1e8))]
#     opt = minimize(_neg_loglike_linear, x0, args=(X, y), method=method, bounds=bounds)
#     if not opt.success and method != "SLSQP":  # tiny-data fallback
#         opt = minimize(_neg_loglike_linear, x0, args=(X, y), method="SLSQP", bounds=bounds)
#     if not opt.success:
#         raise RuntimeError("MLE did not converge: " + opt.message)
#     th = opt.x
#     return th[:k], np.exp(th[k])
# 
# # Q5
# # helper name does NOT start with test_ so pytest won't collect it
# def check_mle_vs_ols(clean_df, years=(1971,1980,1990,2000), tol=1e-6):
#     Xcols = ["const","Educ","Age","Age2","Black","Hispanic","OtherRace"]
#     for yr in years:
#         d = clean_df[clean_df["year"]==yr].copy()
#         if d.empty:
#             continue
#         d["const"] = 1.0
#         X = d[Xcols].to_numpy()
#         y = d["lnw"].to_numpy()
#         ols = sm.OLS(y, X, missing="drop").fit()
#         beta_ols = np.asarray(ols.params)
#         beta_mle, _ = mle_linear_normal(X, y, method="L-BFGS-B")
#         diff = np.max(np.abs(beta_mle - beta_ols))
#         assert diff < tol, f"Year {yr}: max |β_MLE-β_OLS|={diff:.2e} ≥ {tol}"
#

# mounting google drive - colab
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
from pathlib import Path
DATA_PATH = Path('/content/drive/My Drive/ECON_833/PSID_data.dta')
raw = pd.read_stata(DATA_PATH)
YEAR_COL = 'year'
print(raw.shape)
raw.head()

# Commented out IPython magic to ensure Python compatibility.
# import os
# os.makedirs("tests", exist_ok=True)
# 
# %%writefile tests/test_pset4.py
# import numpy as np
# import pandas as pd
# import statsmodels.api as sm
# from psid_model import clean_raw, check_a, check_b, mle_linear_normal  # NOTE: no test_mle_vs_ols here
# 
# def _toy_clean():
#     df = pd.DataFrame({
#         "hlabinc":[40000, 50000, 45000, 52000],
#         "hannhrs":[2000, 2080, 1800, 1950],
#         "hsex":[1,1,1,1],
#         "hrace":[1,2,5,3],   # White, Black, Hispanic, Other
#         "age":[30,45,50,35],
#         "hyrsed":[16,14,12,18],
#         "year":[1980,1980,1980,1980]
#     })
#     return clean_raw(df)
# 
# def test_selection():
#     clean = _toy_clean()
#     check_a(clean, min_age=25, max_age=60, min_wage=7.0)
# 
# def test_indicators():
#     clean = _toy_clean()
#     check_b(clean)
# 
# def test_mle_matches_ols_synthetic():
#     rng = np.random.default_rng(0)
#     n = 200
#     X = np.c_[np.ones(n), rng.normal(size=(n,3))]
#     beta_true = np.array([0.5, 0.2, -0.1, 0.3])
#     y = X @ beta_true + rng.normal(scale=0.4, size=n)
# 
#     ols = sm.OLS(y, X).fit()
#     beta_ols = np.asarray(ols.params)
# 
#     beta_mle, sigma_mle = mle_linear_normal(X, y, method="L-BFGS-B")
#     assert np.max(np.abs(beta_mle - beta_ols)) < 1e-6
#

import os
os.makedirs("tests", exist_ok=True)

test_code = """\
import numpy as np
import pandas as pd
import statsmodels.api as sm
from psid_model import clean_raw, check_a, check_b, mle_linear_normal  # NOTE: no test_mle_vs_ols here

def _toy_clean():
    df = pd.DataFrame({
        "hlabinc":[40000, 50000, 45000, 52000],
        "hannhrs":[2000, 2080, 1800, 1950],
        "hsex":[1,1,1,1],
        "hrace":[1,2,5,3],   # White, Black, Hispanic, Other
        "age":[30,45,50,35],
        "hyrsed":[16,14,12,18],
        "year":[1980,1980,1980,1980]
    })
    return clean_raw(df)

def test_selection():
    clean = _toy_clean()
    check_a(clean, min_age=25, max_age=60, min_wage=7.0)

def test_indicators():
    clean = _toy_clean()
    check_b(clean)

def test_mle_matches_ols_synthetic():
    rng = np.random.default_rng(0)
    n = 200
    X = np.c_[np.ones(n), rng.normal(size=(n,3))]
    beta_true = np.array([0.5, 0.2, -0.1, 0.3])
    y = X @ beta_true + rng.normal(scale=0.4, size=n)

    ols = sm.OLS(y, X).fit()
    beta_ols = np.asarray(ols.params)

    beta_mle, sigma_mle = mle_linear_normal(X, y, method="L-BFGS-B")
    assert np.max(np.abs(beta_mle - beta_ols)) < 1e-6
"""
with open("tests/test_pset4.py", "w", encoding="utf-8") as f:
    f.write(test_code)
print("Wrote tests/test_pset4.py")

import os, glob
print("CWD:", os.getcwd())
print("Here:", os.listdir("."))
print("Tests:", glob.glob("tests/*.py"))

!PYTHONPATH=/content PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -q tests/test_pset4.py